name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

jobs:
  run_cypress:
    name: Run Cypress
    runs-on: ubuntu-16.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: cypressA.json
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
          browser: chrome
          headless: true
          record: true
          parallel: false
          secrets: '[ "REACT_APP_API_URL"]'
