name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, build and test
        run: |
          yarn install
          yarn build
          yarn test
